"""Make mistakes

Revision ID: 6c0f9317aa0c
Revises: d31a574d30eb
Create Date: 2024-02-26 09:22:49.140757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c0f9317aa0c'
down_revision: Union[str, None] = 'd31a574d30eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('date', sa.TIMESTAMP(), nullable=True))
    op.drop_column('operation', 'dare')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('dare', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('operation', 'date')
    # ### end Alembic commands ###
